### ISSUE TITLE
Create and delete databases over REST

### ISSUE THREAD

**Issue by twobit** [proofrock/ws4sqlite#2]
Would it be possible to start ws4sqlite without specifying a db?
```
ws4sqlite
```

Then a db could be managed with REST:
```
PUT http://localhost:12321/mynewdatabase # Creates db
POST http://localhost:12321/mynewdatabase # Queries db
DELETE http://localhost:12321/mynewdatabase # Deletes db
```

**Comment by proofrock** [comment]
Hi @twobit, thanks for the request. It's interesting, and I think it could work; two things come to my mind:

- what about configurations? A database without configurations is just "open to the world", but of course it could still be useful in a closed environment.
  - maybe they could be passed as the PUT body.

- Some more security provisions should be put in place... I would definitely do this as an opt-in (turned off by default, enabled with `--allow-db-management` or similar) and probably allow to define a "global password" for such operations.

What do you think?

**Comment by twobit** [comment]
> Hi @twobit, thanks for the request. It's interesting, and I think it could work; two things come to my mind:
> 
> * what about configurations? A database without configurations is just "open to the world", but of course it could still be useful in a closed environment.
>   
>   * maybe they could be passed as the PUT body.

On startup a base configuration (yaml/json) could be passed for all tables:

```
ws4sqlite --config base-config.json
```

The base configuration could be overwritten in the PUT body (as json).

> * Some more security provisions should be put in place... I would definitely do this as an opt-in (turned off by default, enabled with `--allow-db-management` or similar) and probably allow to define a "global password" for such operations.
> 
> What do you think?

Sounds good! I think this could be really cool to serve different databases to different users in one instance.

**Comment by proofrock** [comment]
Thank you! I referenced this issue in ROADMAP.md, I'm closing it now.
