### ISSUE TITLE
Typo in Documentation ?

### ISSUE THREAD

**Issue by jgranduel** [proofrock/ws4sqlite#3]
Hi, 

thanks for this project. 
Shouldn't  `storedQueries` be replaced by `storedStatements` in [stored-statements documentation](https://germ.gitbook.io/ws4sqlite/documentation/stored-statements) (or added)?
With `storedQueries`, I get : 
```
{
  "reqIdx": 0,
  "error": "a stored statement is required, but did not find it"
}
```
and no  ` With 2 stored statements` at startup.

**Comment by proofrock** [comment]
Thanks for catching this! It was renamed recently, and I totally forgot to update that part of the docs. Should be ok now.
