### ISSUE TITLE
Any plans for WAL2 / BEGIN CONCURRENT?

### ISSUE THREAD

**Issue by gnat** [proofrock/ws4sqlite#30]
Firstly, awesome project! 👏 Love the backup / vacuum jobs and driver-free access via http! Very flexible tool.

WAL2 would provide some nice advantages to ws4sqlite:

* More concurrent writes per second without batching.
* No infinitely growing WAL file.
* No writing until **COMMIT**.
* More granular "page level" locking (instead of "table level" with WAL).

**Comment by proofrock** [comment]
Thanks! I'll mark this as duplicate of #31
