### ISSUE TITLE
Doesn't seem to be working on Windows 11

### ISSUE THREAD

**Issue by ilovefreesw** [proofrock/ws4sqlite#6]
Tried using it on Chinook DB and it is not running the SQL.

Chinook DB = https://www.sqlitetutorial.net/sqlite-sample-database/

![image](https://user-images.githubusercontent.com/77317006/158367766-18f9c8a6-b795-4111-b66f-384f9569dbfb.png)

**Comment by proofrock** [comment]
It's missing the content type... try and use `-H "Content-Type: application/json"`.

**Comment by proofrock** [comment]
No worries! Thanks!
